version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#  api:
#    build: .
    # TODO: version your project here
#    image: seatgeek.com/user-management:<version>
#    ports:
      # TODO: Map your ports here
#      - "8080:8080"
    # volumes:
    # environment:
    # depends_on:
    # links:
  # TODO: Add any other dependencies you need to run the service
volumes:
   db:
     driver: local
