version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sgeek.com/user-management:0.1
    ports:
      - "8080:8080"
    #volumes:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APP_DBHOST=db
    depends_on:
      - db
    #links:
  # TODO: Add any other dependencies you need to run the service
volumes:
  db_data:
     driver: local
