spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
logging:
  level:
    org.springframework.data.r2dbc: Debug
server.error.include-message: always
server.error.include-binding-errors: always
---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
server.error.include-message: always
server.error.include-binding-errors: always
---
spring:
  profiles: prod
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  logging:
    level:
      org.springframework.data.r2dbc: Debug
server.error.include-message: always
server.error.include-binding-errors: always